name: Generate Enchantments
on:
  workflow_dispatch:
  schedule:
    # Runs at 1am
    - cron: '0 1 * * *'
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: web
          path: data
          
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Execute Gradle build
        run: ./gradlew build
        
      - name: Run built jar
        run: 'java -jar $(find ./build/libs -type f -name *-all.jar)'
        env:
          URL_PREFIX: ${{ secrets.URL_PREFIX }}
        
      - name: Commit Changes
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: data
      
      - name: Open Issue for Any Errors
        if: always() && env.ERROR_VERSION != ''
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/error-version.md